---
title: "Problem Set 3 - Soriano"
output:
  pdf_document: default
  html_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r boilerplate, include=FALSE}
##Boilerplate Items for BDS##
library("tidyverse") 
library("psych")
library("haven")
library("flexsurv")
library("foreign")
library("survival")
library("flexsurv")
rm(list=ls())

#Setup the data directories(different kinds)
df<-read.csv ("ccg803.csv")
source("fitparametric.R")
```

# PROBLEM 1a.
The exponentiated coeffecient for rx is 0.73, which represenets the HR between control and treatment group. The odds of recurrence of leukemia in those that receive dactinomycin in addition to standard therapy is 27% lower than those that undergo stndard treatment.

# Problem 1b
exp(.7435228)

```{r, results=TRUE}
### 1a
s.df = with(df, Surv(duration, relapse))
coxFit.1a = coxph(s.df ~ rx, data=df)
summary (coxFit.1a)

### 1b
coxFit.1b = coxph(s.df ~ rx + wbc + age, data=df)
summary(coxFit.1b)

### 1c
# dichotomize WBC based on the cutoff of 100
df$wbcHigh [df$wbc >= 99] <- 1
df$wbcHigh [df$wbc < 100] <- 0
summary(coxph(s.df ~ rx + wbc + age + strata(wbcHigh), data=df))

#perform test of hypothesis 

### 1d
summary(coxph(s.df ~ rx + wbc + age + strata(institution), data=df))

### 1e
coxFit.1e = coxph(s.df ~ rx, data=df, ties="exact")
plot (survfit(coxFit.1e,newdata=data.frame(rx=1),conf.type="none"), col=2,lwd=2)
lines(survfit(coxFit.1e,newdata=data.frame(rx=0),conf.type="none"),col=4,lwd=2)
legend("bottomleft",fill=c(2,4),legend=c("Treatment","control"),bty='n')

profile1=data.frame(wbc40=1,wbc200=0)
profile2=data.frame(wbc40=0,wbc00=1)
coxFit.1e = coxph(s.df ~ rx + df$age==5 + wbc40 + wbc200, data=df, ties="exact")
plot (survfit(coxFit.1e,newdata=profile1,conf.type="none"), col=2,lwd=2)
lines(survfit(coxFit.1e,newdata=data.frame(rx=0),conf.type="none"),col=4,lwd=2)
legend("bottomleft",fill=c(2,4),legend=c("Treatment","control"),bty='n')


herpes$type2=as.numeric(herpes$type==2)
herpes$type3=as.numeric(herpes$type==3)
coxfit=coxph(s.herpes~type2+type3+duration,data=herpes)

#build age and wbc groups

herpes$type2=as.numeric(herpes$type==2)
herpes$type3=as.numeric(herpes$type==3)
coxfit=coxph(s.herpes~type2+type3+duration,data=herpes)
profile1=data.frame(type2=0,type3=0,duration=7)
profile2=data.frame(type2=1,type3=0,duration=7)
profile3=data.frame(type2=0,type3=1,duration=7)
profile4=data.frame(type2=0,type3=0,duration=21)
profile5=data.frame(type2=1,type3=0,duration=21)
profile6=data.frame(type2=0,type3=1,duration=21)
plot(survfit(coxfit,newdata=profile1,conf.type="none"),col=4,lwd=1.5)
lines(survfit(coxfit,newdata=profile2,conf.type="none"),col=2,lwd=1.5)
lines(survfit(coxfit,newdata=profile3,conf.type="none"),
col="darkgreen",lwd=1.5)
lines(survfit(coxfit,newdata=profile4,conf.type="none"),col=4,
lwd=1.5,lty=2)
lines(survfit(coxfit,newdata=profile5,conf.type="none"),col=2,
lwd=1.5,lty=2)
lines(survfit(coxfit,newdata=profile6,conf.type="none"),
col="darkgreen",lwd=1.5,lty=2)
legend("topright",
legend=c("type1/duration=1wk","type2/duration=1wk",
"type3/duration=1wk","type1/duration=3wks",
"type2/duration=3wks","type3/duration=3wks"),
col=c(4,2,"darkgreen",4,2,"darkgreen"),lwd=rep(2,6),
lty=c(rep(1,3),rep(2,3)),cex=.7,bty="n")
```
# PROBLEM 2

```{r}
#setup
addicts<-read.csv ("addicts.csv")
source("fitparametric.R")
```

```{r}
##Problem 2a
s.addicts = with(addicts, Surv(time, event))
coxFit.2a = coxph(s.addicts ~ dose + prison + clinic, data=addicts)
summary (coxFit.2a)

##Problem 23b
coxFit.2b = coxph(s.addicts ~ dose + prison + strata(clinic), data=addicts)
summary (coxFit.2b)
```
